name: Debug Doctor

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  run-doctor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Accept Android Licenses
        run: yes | sudo /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses --sdk_root=/usr/local/lib/android/sdk

      - name: Cache Android NDK
        id: cache-ndk
        uses: actions/cache@v5
        with:
          path: /usr/local/lib/android/sdk/ndk/25.2.9519653
          key: ${{ runner.os }}-ndk-25.2.9519653

      - name: Install Android NDK
        if: steps.cache-ndk.outputs.cache-hit != 'true'
        run: yes | sudo /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --install "ndk;25.2.9519653" --sdk_root="/usr/local/lib/android/sdk"

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Flutter Doctor
        run: flutter doctor -v
